version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/example
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 900
      runas: root
file_exists_behavior: OVERWRITE
