services:
    php:
        build:
            args:
                user: ${PHP_CONTAINER_USER}
                uid: 1000
            context: .
            dockerfile: Dockerfile-php
        container_name: ${PHP_CONTAINER_NAME}
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - php-app-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
    caddy:
        build:
            context: .
            dockerfile: Dockerfile-caddy
        restart: unless-stopped
        working_dir: /var/www
        environment:
            FASTCGI_TARGET: ${PHP_CONTAINER_NAME}
        ports:
            - "80:80"
            - "443:443"
            - "2016:2016"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./:/var/www
            - caddy_data:/data
            - caddy_config:/config
            - ./caddy_certs:/root/certs # to sync mkcert certificates to Caddy
        networks:
            - php-app-network
        container_name: ${CADDY_CONTAINER_NAME}

    db:
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - php-app-network
        container_name: ${DB_CONTAINER_NAME}

volumes:
    caddy_data:
    caddy_config:
    pg_data:

networks:
    php-app-network:
        driver: bridge
